### ISSUE TITLE
docs(e2e adopter journey): Adapt prerequisites

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#452]
## Tasks

- [x] Describe technical requirements
- [x] Documen used/needed ports
- [x] Are any dependency checks for helm available? To fasten the ports lookup?
