### ISSUE TITLE
docs(e2e adopter journey): Adapt/Extend connect part

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/eclipse-tractusx.github.io#456]
## What

The [preperation documentation](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/connect/prepareInfrastructure.md) needs some detailed updates. It would be better to also document the different steps, since we are refering to Kind, it would be good to document also the really needed steps for installation.

For [deploy components](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/connect/deployComponents.md) a more step by step guide is needed. Related to the different commands which needs to be executed.

## Tasks

- [x] Extend [preperation documentation](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/connect/prepareInfrastructure.md)
- [x] Extend [deploy components](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/connect/deployComponents.md)
- [x] Move this section to [prerequisites](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/feat/tutorials/docs/tutorials/e2e/prerequisites/prerequisites.md), it it fits better
