### ISSUE TITLE
[Business Partner KIT] Update Operation View

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/eclipse-tractusx.github.io#990]
The Business Partner Kit's operation view contains some outdated information that should be removed or changed. Since the BPDM's [INSTALL](https://github.com/eclipse-tractusx/bpdm/blob/release/6.1.x/INSTALL.md) file contains the newest information on how to run BPDM I would include a link for additional information as well.

## Tasks

- [x] Profiles examples should no longer reference outdated 'auth' profiles
- [x] Cleaning Service Dummy has no API and no ingress
- [x] Reference to the BPDM repositories INSTALL file for more examples

**Comment by SujitMBRDI** [comment]
Covered expected changes under pull request [#988](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/988)
